# This is a basic workflow to help you get started with Actions

name: TESTER

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create env file
        run: |
          cd ./config
          mkdir environments
          cd environments
          echo VERSION = 0.0.1 >> ./config/environments/.env
          echo NODE_ENV = test_remote >> ./config/environments/.env

      - name: Install Dependencies
        run: npm install

      - name: Test Deployment
        run: |
          npm install sequelize-cli -g
          npm run test:remote
